---

  - name: Add nginx yum repository
    copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644

  - name: Install nginx
    yum: name=nginx state=latest

  - name: Start nginx
    service: name=nginx state=running enabled=yes