---
- hosts: vagrants
  become: true

  vars_files:
    - java/vars/main.yml

  vars:
    groovy_download: https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.6.zip
    groovy_name: groovy-2.4.6
    groovy_archive: "{{ download_directory }}/{{ groovy_name }}.zip"
    groovy_directory: /usr/groovy
    groovy_link: "{{ groovy_directory }}/default"

  tasks:
    - include: java/tasks/main.yml

    - name: Install unzip
      yum: name=unzip state=latest

    - name: Create Download directory
      file: state=directory path={{ download_directory }}

    - name: Download Groovy
      get_url: url={{ groovy_download }} dest={{ groovy_archive }}

    - name: Extract Groovy archive
      unarchive: src={{ groovy_archive }} dest={{ download_directory }} copy=no creates={{ download_directory }}/{{ groovy_name }}

    - name: Create Groovy directory
      file: state=directory path={{ groovy_directory }}

    - name: Move Groovy to final directory
      command: mv {{ download_directory }}/{{ groovy_name }} {{ groovy_directory }}

    - name: Fix ownership
      file: state=directory path={{ groovy_directory }}/{{ groovy_name }} owner=root group=root recurse=yes

    - name: Create symbolic link
      file: dest={{ groovy_link }} src={{ groovy_directory }}/{{ groovy_name }} state=link

    - name: Set GROOVY_HOME
      shell: echo 'export GROOVY_HOME={{ groovy_link }}' >> /etc/profile.d/groovy.sh

    - name: Set Path
      shell: echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> /etc/profile.d/groovy.sh

    - name: Source command
      shell: source /etc/profile.d/groovy.sh
